### ISSUE TITLE
Decryption fails with LineageOS 16 and twrp 3.3.1

### ISSUE THREAD

**Issue by cweiske** [TeamWin/android_device_xiaomi_dipper#1]
Using the official twrp 3.3.1, decryption of data during mount fails with:

> pattern failed, please try again

When using "TWRP 3.3.1-0 Unofficial by mauronofrio" from https://forum.xda-developers.com/mi-8/development/recovery-unofficial-twrp-recovery-t3893823 decryption works fine.

I am running LineageOS 16.

**Comment by CyborgCriminal** [comment]
Yeah awesome life is great with dipper PE with TWRP

**Comment by cweiske** [comment]
This problem is gone with `twrp-3.7.0_9-0-dipper.img`.
